spring:
  profiles:
    # 启用对应版本配置
    active: dev
  jackson:
    # JSON日期格式化
    date-format:
    # JSON日期格式化设置时区为上海
    time-zone: Asia/Shanghai
  mvc:
    # 日期格式化
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞时间，默认-1
        max-wait: 10000ms
        # 最大控线连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5
  # rabbitmq
  rabbitmq:
    host:
    username:
    password:
    port: 5672
    virtual-host: /
    # 开启确认机制
    publisher-confirm-type: correlated
  application:
    name: user-serve-consumer


mybatis-plus:
  # 设置别名
  type-aliases-package: com.tian.userserver.pojo
  # 加载映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
  # 关闭驼峰命名映射
#  configuration:
#    map-underscore-to-camel-case: true


# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/	#注册中心url
    fetch-registry: true
    register-with-eureka: true

############# 自定义配置  #############

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: vue-server-secret
  # Jwt 的超期限时间（60*60）*24*14
  expiration: 1209600
  # Jwt负载中拿到开头
  tokenHead: Bearer

# redis过期时间
redis:
  expire: 1209600

# 密盐key
aes:
  secretKey: com0tianhuanying
