spring:
  profiles:
    # 启用对应版本配置
    active: dev
  jackson:
    # JSON日期格式化
    date-format: yyyy-MM-dd
    # JSON日期格式化设置时区为上海
    time-zone: Asia/Shanghai
  mvc:
    # 日期格式化
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  # redis配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 1
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞时间，默认-1
        max-wait: 10000ms
        # 最大控线连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5

mybatis-plus:
  # 设置别名
  type-aliases-package: com.tian.itemserver.pojo
  # 加载映射文件
  mapper-locations: classpath*:/mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 关闭驼峰命名映射
#  configuration:
#    map-underscore-to-camel-case: true


############# 自定义配置  #############
# redis过期时间
redis:
  expire: 60000

