spring:
  # rabbitmq
  rabbitmq:
    host: 119.3.37.218
    username: admin
    password: admin
    port: 5672
    virtual-host: /
  # 邮箱
  mail:
    username: 1097598544@qq.com
    password: zieytmaxgkgnhhch
    host: smtp.qq.com
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
