server:
  port: 9009
spring:
  cloud:
    gateway:
      routes:
        - id: service-hi
          uri: lb://item-cloud-provider # lb 表示负载均衡loadbalance，SERVICE-HI是服务名称
          predicates:
            - Path=/demo/** # 所有demo开头的请求走这个路由
          filters:
            - StripPrefix=1 # 转发之前将/demo去掉
  application:
    name: spring-cloud-gateway
# eureka 注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#      defaultZone: http://localhost:7001/eureka/
