server:
  port: 9527

spring:
  application:
    name: springcloud-zuul #微服务名称

# eureka 注册中心配置
eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://localhost:7001/eureka/
  instance: #实例的id
    instance-id: eureka9527.com
    prefer-ip-address: true # 显示ip
info:
  app.name: tian.springcloud # 项目名称
  company.name: tiantian # 公司名称


