server:
  port: 7001

# eureka配置
eureka:
  instance:
    hostname: localhost # eureka服务端实例名称
  client:
    register-with-eureka: false # 表示是否向rureka注册中心注册自己
    fetch-registry: false # fetch-registry为false表示自己就是注册中心
    service-url:  # 监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
