spring:
  # rabbitmq
  rabbitmq:
    host:
    username:
    password:
    port: 5672
    virtual-host: /
  # 邮箱
  mail:
    username: 1097598544@qq.com
    password:
    host: smtp.qq.com
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
